// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductCatalogService.Data;

#nullable disable

namespace ProductCatalogService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240723103317_AddProductCatalogAndSeedTable")]
    partial class AddProductCatalogAndSeedTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductCatalogService.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Clothing & Apparel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Health & Beauty"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Books & Media"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Toys & Games"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Pets"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jewelry & Accessories"
                        });
                });

            modelBuilder.Entity("ProductCatalogService.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Twin Lens Camera",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "Twin Lens Camera",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Compact SLR Camera",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "Compact SLR Camera",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Nikkormat SLR Camera",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "Nikkormat SLR Camera",
                            Price = 1900.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Compact Digital Camera",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "Compact Digital Camera",
                            Price = 1900.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "Instamatic Camera",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "Instamatic Camera",
                            Price = 1900.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            Description = "Tripod",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "Tripod",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            Description = "Vintage Folding Camera",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "Vintage Folding Camera",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            Description = "Camera Lens",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "Camera Lens",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 9,
                            Description = "Instant Camera",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "Instant Camera",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            Description = "USB Cable",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "USB Cable",
                            Price = 1600.0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Ethernet Cable",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "Ethernet Cable",
                            Price = 100.0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Clacky Keyboard",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "Clacky Keyboard",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "Hard Drive",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "Hard Drive",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Description = "Gaming PC",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "Gaming PC",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Description = "High Performance RAM",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "High Performance RAM",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            Description = "Curvy Monitor",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "Curvy Monitor",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 7,
                            Description = "32-Inch Monitor",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "32-Inch Monitor",
                            Price = 1900.0
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 8,
                            Description = "Wireless Optical Mouse",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "Wireless Optical Mouse",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 9,
                            Description = "Tablet",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "Tablet",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 10,
                            Description = "Laptop",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "Laptop",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            Description = "Grey Fabric Sofa",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "Grey Fabric Sofa",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Description = "Hi-Top Basketball Shoe",
                            ImageUrl = "https://readonlydemo.vendure.io/assets/preview/3c/xavier-teo-469050-unsplash__preview.jpg?w=200&h=200",
                            Name = "Hi-Top Basketball Shoe",
                            Price = 250.0
                        });
                });

            modelBuilder.Entity("ProductCatalogService.Models.Product", b =>
                {
                    b.HasOne("ProductCatalogService.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductCatalogService.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
